### ISSUE TITLE
Error in kubric_eval.py

### ISSUE THREAD

**Issue by astroyh** [UT-Austin-RPL/FORGE#2]
There is an error in kubric_eval.py(line 296), where model.module.render function return no depth even if render_depth is set true, which will result in an error in volume_render.py line 67: rendered_imgs, rendered_silhouettes, rendered_depth = rendered.split([C, 1, 1], dim=-1). (C + 1 + 1=18, and the shape of rendered is […,17]

**Comment by hwjiang1510** [comment]
Hi,

Did you modified the rendering function following the readme?
